In [4]:
import pandas as pd

In [5]:
data_2019 = pd.read_csv('results_data/data_2019.csv')
data_2019

C:\Users\noyon\AppData\Local\Temp\ipykernel_34832\2222163162.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  data_2019 = pd.read_csv('results_data/data_2019.csv')

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Month
0,1793,2019-07-01 00:00:36.6150,2019-07-01 00:30:30.5940,3186,Grove St PATH,40.719586,-74.043117,3198,Heights Elevator,40.748716,-74.040443,29595,Subscriber,1978,1,July 2019
1,434,2019-07-01 00:02:54.6150,2019-07-01 00:10:09.0370,3206,Hilltop,40.731169,-74.057574,3280,Astor Place,40.719282,-74.071262,29647,Subscriber,1988,1,July 2019
2,251,2019-07-01 00:03:27.5670,2019-07-01 00:07:38.6080,3186,Grove St PATH,40.719586,-74.043117,3205,JC Medical Center,40.716540,-74.049638,26271,Subscriber,1986,1,July 2019
3,636,2019-07-01 00:03:56.1690,2019-07-01 00:14:32.4180,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,26225,Customer,1996,2,July 2019
4,623,2019-07-01 00:04:16.2060,2019-07-01 00:14:40.0500,3206,Hilltop,40.731169,-74.057574,3281,Leonard Gordon Park,40.745910,-74.057271,29230,Customer,1989,1,July 2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
221737,77,2019-11-30 23:30:07.7850,2019-11-30 23:31:25.7730,3638,Washington St,40.724294,-74.035483,3202,Newport PATH,40.727224,-74.033759,29492,Subscriber,1979,1,NaN
221738,145,2019-11-30 23:40:45.3790,2019-11-30 23:43:10.5660,3211,Newark Ave,40.721525,-74.046305,3278,Monmouth and 6th,40.725685,-74.048790,40971,Subscriber,1978,1,NaN
221739,99,2019-11-30 23:41:55.3310,2019-11-30 23:43:34.3320,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,26198,Subscriber,1991,1,NaN
221740,594,2019-11-30 23:52:50.2410,2019-12-01 00:02:44.2960,3213,Van Vorst Park,40.718489,-74.047727,3639,Harborside,40.719252,-74.034234,29527,Subscriber,1981,1,NaN
221741,329,2019-11-30 23:56:27.6680,2019-12-01 00:01:57.0120,3185,City Hall,40.717732,-74.043845,3267,Morris Canal,40.712419,-74.038526,26163,Subscriber,1977,1,NaN

In [6]:
data_2020 = pd.read_csv('results_data/data_2020.csv')
data_2020

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Month
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2,January 2020
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2,January 2020
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1,January 2020
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0,January 2020
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2,January 2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
66696,296,2020-03-31 22:50:39.0410,2020-03-31 22:55:35.5980,3191,Union St,40.718211,-74.083639,3694,Jackson Square,40.711130,-74.078900,42145,Subscriber,1994,1,March 2020
66697,147,2020-03-31 23:09:15.9690,2020-03-31 23:11:43.5310,3640,Journal Square,40.733670,-74.062500,3206,Hilltop,40.731169,-74.057574,42110,Subscriber,1991,1,March 2020
66698,364,2020-03-31 23:17:02.0240,2020-03-31 23:23:06.8200,3195,Sip Ave,40.730897,-74.063913,3679,Bergen Ave,40.722104,-74.071455,42550,Subscriber,1986,1,March 2020
66699,1217,2020-03-31 23:36:10.6430,2020-03-31 23:56:27.8120,3267,Morris Canal,40.712419,-74.038526,3276,Marin Light Rail,40.714584,-74.042817,42115,Subscriber,1986,1,March 2020
66700,846,2020-03-31 23:37:21.1840,2020-03-31 23:51:28.1220,3195,Sip Ave,40.730897,-74.063913,3193,Lincoln Park,40.724605,-74.078406,42362,Subscriber,1965,1,March 2020

In [8]:
total_merged_data_df = pd.concat([data_2020,data_2019],ignore_index=True)
total_merged_data_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Month
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,2,January 2020
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,2,January 2020
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,1,January 2020
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,0,January 2020
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,2,January 2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288438,77,2019-11-30 23:30:07.7850,2019-11-30 23:31:25.7730,3638,Washington St,40.724294,-74.035483,3202,Newport PATH,40.727224,-74.033759,29492,Subscriber,1979,1,NaN
288439,145,2019-11-30 23:40:45.3790,2019-11-30 23:43:10.5660,3211,Newark Ave,40.721525,-74.046305,3278,Monmouth and 6th,40.725685,-74.048790,40971,Subscriber,1978,1,NaN
288440,99,2019-11-30 23:41:55.3310,2019-11-30 23:43:34.3320,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,26198,Subscriber,1991,1,NaN
288441,594,2019-11-30 23:52:50.2410,2019-12-01 00:02:44.2960,3213,Van Vorst Park,40.718489,-74.047727,3639,Harborside,40.719252,-74.034234,29527,Subscriber,1981,1,NaN
288442,329,2019-11-30 23:56:27.6680,2019-12-01 00:01:57.0120,3185,City Hall,40.717732,-74.043845,3267,Morris Canal,40.712419,-74.038526,26163,Subscriber,1977,1,NaN

In [9]:
# Dictionary mapping values in the 'gender' column to new values
mapping = {0: 'Unknown', 1: 'Male', 2: 'Female'}

# Use the 'map' method to change the values in the 'gender' column
total_merged_data_df['gender'] = total_merged_data_df['gender'].map(mapping)

# Show DataFrame
total_merged_data_df

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender,Month
0,226,2020-01-01 00:04:50.1920,2020-01-01 00:08:37.0370,3186,Grove St PATH,40.719586,-74.043117,3211,Newark Ave,40.721525,-74.046305,29444,Subscriber,1984,Female,January 2020
1,377,2020-01-01 00:16:01.6700,2020-01-01 00:22:19.0800,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,26305,Subscriber,1989,Female,January 2020
2,288,2020-01-01 00:17:33.8770,2020-01-01 00:22:22.4420,3186,Grove St PATH,40.719586,-74.043117,3269,Brunswick & 6th,40.726012,-74.050389,29268,Customer,1989,Male,January 2020
3,435,2020-01-01 00:32:05.9020,2020-01-01 00:39:21.0660,3195,Sip Ave,40.730897,-74.063913,3280,Astor Place,40.719282,-74.071262,29278,Customer,1969,Unknown,January 2020
4,231,2020-01-01 00:46:19.6780,2020-01-01 00:50:11.3440,3186,Grove St PATH,40.719586,-74.043117,3276,Marin Light Rail,40.714584,-74.042817,29276,Subscriber,1983,Female,January 2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
288438,77,2019-11-30 23:30:07.7850,2019-11-30 23:31:25.7730,3638,Washington St,40.724294,-74.035483,3202,Newport PATH,40.727224,-74.033759,29492,Subscriber,1979,Male,NaN
288439,145,2019-11-30 23:40:45.3790,2019-11-30 23:43:10.5660,3211,Newark Ave,40.721525,-74.046305,3278,Monmouth and 6th,40.725685,-74.048790,40971,Subscriber,1978,Male,NaN
288440,99,2019-11-30 23:41:55.3310,2019-11-30 23:43:34.3320,3792,Columbus Dr at Exchange Pl,40.716870,-74.032810,3639,Harborside,40.719252,-74.034234,26198,Subscriber,1991,Male,NaN
288441,594,2019-11-30 23:52:50.2410,2019-12-01 00:02:44.2960,3213,Van Vorst Park,40.718489,-74.047727,3639,Harborside,40.719252,-74.034234,29527,Subscriber,1981,Male,NaN
288442,329,2019-11-30 23:56:27.6680,2019-12-01 00:01:57.0120,3185,City Hall,40.717732,-74.043845,3267,Morris Canal,40.712419,-74.038526,26163,Subscriber,1977,Male,NaN

In [10]:
total_merged_data_df.to_csv('results_data/total_merged_data.csv', index=False)